//! `render_displays()`: the per-monitor `hyprland.lua` fragment, and the gate `render_all()`
//! reaches it through.

use std::fmt::Write as _;

use garage_core::fs::lua::write_lua;
use garage_core::pyrepr::py_format_g;

use crate::cx::RenderCx;
use crate::displays::{
    load_display_config, mirror_targets, DisplayEntry, DisplayLayout, LayoutValue, NumberError,
};
use crate::error::RenderError;
use crate::lua::escape::lua_string;

/// `render_displays()` (garage:2456-2492): the per-monitor fragment's text.
///
/// # Errors
///
/// [`RenderError::Number`] when a hand-edited record puts something `int()` or `float()`
/// refuses where a coordinate, a scale, a transform or a VRR mode belongs.
pub fn display_fragment_text(layout: &DisplayLayout) -> Result<String, RenderError> {
    let mirrors = mirror_targets(&layout.displays);
    let mut text = String::from("-- Generated by garage. Edit displays.toml instead.");
    if !layout.primary.is_empty() {
        let _ = write!(text, "\nPRIMARY_MONITOR = {}", lua_string(&layout.primary));
    }
    // Sources ahead of the mirrors that name them. `sorted(key=lambda entry: ... in mirrors)`
    // is a stable sort on a boolean, so the two groups keep their own relative order.
    let mut ordered: Vec<&DisplayEntry> = layout.displays.iter().collect();
    ordered.sort_by_key(|entry| mirrors.iter().any(|(name, _)| *name == entry.output()));
    for entry in ordered {
        let output = lua_string(&entry.output());
        if !entry.enabled() {
            let _ = write!(
                text,
                "\nhl.monitor({{ output = {output}, disabled = true }})"
            );
            continue;
        }
        let mode = lua_string(
            &entry
                .get("mode")
                .map_or_else(|| "preferred".to_owned(), LayoutValue::py_str),
        );
        let scale = lua_string(&py_format_g(number(entry.get("scale"), 1.0)?));
        let transform = integer(entry.get("transform"), 0)?;
        let source = mirrors
            .iter()
            .find(|(name, _)| *name == entry.output())
            .map(|(_, source)| source.clone())
            .unwrap_or_default();
        let placement = if source.is_empty() {
            format!(
                "position = {}",
                lua_string(&format!(
                    "{}x{}",
                    integer(entry.get("x"), 0)?,
                    integer(entry.get("y"), 0)?
                ))
            )
        } else {
            format!("mirror = {}", lua_string(&source))
        };
        // Clamped rather than validated: Hyprland only accepts -1..3 and rejects the whole
        // rule otherwise, and a bad vrr on one display must not take every monitor rule down
        // with it. -1 inherits misc:vrr.
        let vrr = integer(entry.get("vrr"), -1)?.clamp(-1, 3);
        let _ = write!(
            text,
            "\nhl.monitor({{ output = {output}, mode = {mode}, {placement}, \
             scale = {scale}, transform = {transform}, vrr = {vrr} }})"
        );
    }
    text.push('\n');
    Ok(text)
}

/// `float(item.get(key, fallback))`.
fn number(value: Option<&LayoutValue>, fallback: f64) -> Result<f64, NumberError> {
    value.map_or(Ok(fallback), LayoutValue::py_float)
}

/// `int(item.get(key, fallback))`.
fn integer(value: Option<&LayoutValue>, fallback: i64) -> Result<i64, NumberError> {
    value.map_or(Ok(fallback), LayoutValue::py_int)
}

/// Write the per-monitor `hyprland.lua` fragment from a layout already in hand.
///
/// The layout is an argument rather than a read, because two of the three callers do not have
/// one on disk: `apply_display_layout()` renders the *candidate* it is checking, and
/// `display_finish()` renders the one it just confirmed. `render_all()`'s own call is the
/// only one that loads the file first, and it does so itself -- as the Python's does.
///
/// # Errors
///
/// Whatever [`display_fragment_text`] refuses, and [`RenderError::Lua`] if the fragment does
/// not parse or cannot be installed.
pub fn render_displays(cx: &RenderCx<'_>, layout: &DisplayLayout) -> Result<(), RenderError> {
    let text = display_fragment_text(layout)?;
    write_lua(&cx.paths().fragments.displays, &text, cx.lua())?;
    Ok(())
}

/// `layout = load_display_config(); if layout["displays"]: render_displays(layout) else:
/// DISPLAY_FRAGMENT.unlink(missing_ok=True)` (garage:3518-3522).
///
/// The Python writes those four lines inline at the end of `render_all()`; they live beside
/// the renderer they gate so that there is one copy of them and so that the gate itself is
/// testable without standing up a whole render. [`crate::all::render_all`] is still the only
/// caller, and calls it in the same position.
///
/// A `displays.toml` with no `[[display]]` entries at all -- true of every machine nothing
/// has ever run `display-confirm` against -- takes the `else` branch: the stale fragment is
/// taken away rather than a fragment with no monitor rules being written, which would pin the
/// session to nothing instead of falling back to `config.monitors`' catch-all rule.
///
/// # Errors
///
/// [`RenderError::Toml`] from the read, [`RenderError::Remove`] if an empty layout's stale
/// fragment cannot be taken away, and otherwise whatever [`render_displays`] returns.
pub fn render_saved_displays(cx: &RenderCx<'_>) -> Result<(), RenderError> {
    let layout = load_display_config(&cx.paths().host.displays)?;
    if !layout.displays.is_empty() {
        return render_displays(cx, &layout);
    }
    let fragment = &cx.paths().fragments.displays;
    match std::fs::remove_file(fragment) {
        Ok(()) => Ok(()),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(source) => Err(RenderError::Remove {
            path: fragment.clone(),
            source,
        }),
    }
}
