//! `render_workspaces()`: publish the workspace plan for `config.variables` to read.
//!
//! Not loaded from `hyprland.lua`'s override block the way the other generated fragments
//! are: `config.binds` is required before that block runs, and it has to build its per-slot
//! binds from the same plan the workspace rules use. `config.variables`, which is required
//! before `config.binds`, picks the fragment up instead -- the load order is the reason this
//! renderer's file sits where it does rather than beside its siblings.
//!
//! `workspace_plan()` behind it is one of two shapes. Shared mode is one unpinned group whose
//! `monitor` is left empty in the emitted table, which is what tells the Lua side to address
//! workspaces by id instead of by output. Per-display mode calls `per_display_groups()`,
//! which is documented in [`crate::workspaces::blocks`] alongside the allocator it depends
//! on -- the plan itself does not decide which ids a display owns, it only asks.
//!
//! An empty plan -- nothing detected and nothing saved -- removes the fragment rather than
//! writing one that pins workspaces to connectors that may no longer exist. Falling back to
//! no fragment at all falls back to the plan `variables.lua` already carries by default,
//! which is a plan that always has at least one group.
//!
//! `hyprctl monitors` is read from here, through [`RenderCx::monitors`]'s question rather
//! than an instruction -- see the crate's own top-level doc and [`crate::workspaces::blocks`]
//! for why the saved layout leads and the live list is only folded in on top.

use std::fmt::Write as _;

use garage_core::fs::lua::write_lua;
use garage_core::schema::enums::WorkspaceMode;
use garage_core::schema::newtypes::{BlockId, ConnectorName};

use crate::cx::RenderCx;
use crate::error::RenderError;
use crate::lua::escape::lua_string;
use crate::workspaces::blocks::per_display_groups;
use crate::workspaces::{WorkspaceGroup, WorkspacePlan};

/// `HYPR_PRIMARY_MONITOR`, read at call time exactly as `os.environ.get()` does.
///
/// The Python binds nothing about the primary at import: `workspace_outputs()` reads the
/// environment on every call, so a session that exports the variable after this process
/// started would still be honoured. The read is here, at the outermost entry point, rather
/// than down in the allocator, so every function below it takes the value as an argument and
/// a test can name it without touching the process environment.
fn primary_from_environment() -> String {
    std::env::var("HYPR_PRIMARY_MONITOR").unwrap_or_default()
}

/// The plan the compositor should be running, with the primary named explicitly.
///
/// # Errors
///
/// Whatever [`per_display_groups`] fails with. Shared mode reads no file and cannot fail.
pub fn workspace_plan_for(
    cx: &RenderCx<'_>,
    primary_environment: &str,
) -> Result<WorkspacePlan, RenderError> {
    let workspaces = &cx.prefs().workspaces;
    if workspaces.mode == WorkspaceMode::Shared {
        // One unpinned group. Its monitor is empty, which is what tells the Lua side to
        // leave `monitor` off the rule and to address workspaces by id.
        return Ok(WorkspacePlan {
            mode: WorkspaceMode::Shared,
            groups: vec![WorkspaceGroup {
                monitor: ConnectorName::from(""),
                // `"first": 1`. Spelled as block zero's first id rather than as a literal,
                // because that is the one infallible way to name a `WorkspaceId` -- the
                // guarded constructor has no unwrap-free sibling and this crate may not
                // unwrap -- and because it is the same arithmetic per-display mode uses.
                first: BlockId::new(0).first(),
                count: u32::try_from(workspaces.shared_count.get()).unwrap_or(1),
            }],
        });
    }
    Ok(WorkspacePlan {
        mode: WorkspaceMode::PerDisplay,
        groups: per_display_groups(cx, primary_environment)?,
    })
}

/// The plan the compositor should be running.
///
/// # Errors
///
/// Whatever [`workspace_plan_for`] fails with.
pub fn workspace_plan(cx: &RenderCx<'_>) -> Result<WorkspacePlan, RenderError> {
    workspace_plan_for(cx, &primary_from_environment())
}

/// The fragment's text, or `None` when the plan has no groups at all.
fn fragment_text(plan: &WorkspacePlan) -> Option<String> {
    if plan.groups.is_empty() {
        return None;
    }
    let mut text = String::from("-- Generated by garage. Edit preferences.toml instead.\n");
    text.push_str("WORKSPACE_PLAN = {\n");
    let _ = writeln!(text, "    mode = {},", lua_string(plan.mode.as_str()));
    text.push_str("    groups = {\n");
    for group in &plan.groups {
        let _ = writeln!(
            text,
            "        {{ monitor = {}, first = {}, count = {} }},",
            lua_string(group.monitor.as_str()),
            group.first.get(),
            group.count
        );
    }
    text.push_str("    },\n}\n");
    Some(text)
}

/// Write the workspace plan for `config.variables` to read.
///
/// # Errors
///
/// [`RenderError::Toml`] or [`RenderError::Atomic`] from the allocator underneath,
/// [`RenderError::Lua`] if the fragment does not parse or cannot be installed, and
/// [`RenderError::Remove`] if an empty plan's fragment cannot be taken away.
pub fn render_workspaces(cx: &RenderCx<'_>) -> Result<(), RenderError> {
    render_workspaces_for(cx, &primary_from_environment())
}

/// [`render_workspaces`] with the primary named explicitly. See
/// [`primary_from_environment`].
///
/// # Errors
///
/// As [`render_workspaces`].
pub fn render_workspaces_for(
    cx: &RenderCx<'_>,
    primary_environment: &str,
) -> Result<(), RenderError> {
    let plan = workspace_plan_for(cx, primary_environment)?;
    let fragment = &cx.paths().fragments.workspaces;
    let Some(text) = fragment_text(&plan) else {
        // Nothing detected and nothing saved. Leaving the fragment behind would pin
        // workspaces to connectors that may no longer exist; removing it falls back to the
        // plan tracked in variables.lua, which always has one.
        return match std::fs::remove_file(fragment) {
            Ok(()) => Ok(()),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
            Err(source) => Err(RenderError::Remove {
                path: fragment.clone(),
                source,
            }),
        };
    };
    write_lua(fragment, &text, cx.lua())?;
    Ok(())
}
