#!/bin/sh

inhibitor="lock"

cleanup() {
    timeout 2 qs -c garage ipc call notifications release "$inhibitor" >/dev/null 2>&1 || true
}

trap cleanup EXIT HUP INT TERM
timeout 2 qs -c garage ipc call shell closeNotifications >/dev/null 2>&1 || true
timeout 2 qs -c garage ipc call notifications inhibit "$inhibitor" >/dev/null 2>&1 || true
hyprlock
