//! Tests for [`crate::toml_emit`], split into their own file to keep that module under the
//! workspace's 500-line file-shape rule -- the same reason `garage-render`'s
//! `render_parity_tests.rs` is a sibling file rather than an inline `mod tests` block.

use crate::toml_emit::{dump_toml, json_dumps, json_string, toml_value, Document, Section, Value};

/// Generated by running the Python `toml_value`/`dump_toml` over the
/// document `preferences_delta()` builds, and checked in. The test never
/// shells out to python3 -- the fixture *is* the record of what it said.
const DOCUMENT: &str = include_str!("../testdata/document.toml");
/// `<hex of the UTF-8 input> \t json.dumps(s, ensure_ascii=False)`.
const JSON_STRINGS: &str = include_str!("../testdata/json_str.txt");

/// A preferences.toml delta with the shapes a real one has: the schema
/// stamp, departures in three sections in defaults order, an int, a bool,
/// integral and non-integral floats, a path with both quote characters in
/// it, and a section holding containers that have to be dropped.
fn preferences_delta() -> Document {
    let mut document = Document::new();
    let mut schema = Section::new();
    schema.push("preferences_version", Value::Int(5));
    document.push("schema", schema);

    let mut appearance = Section::new();
    for (key, value) in [
        (
            "wallpaper_dark",
            Value::Str("/home/rizki/Pictures/it's \"dark\".png".to_string()),
        ),
        ("accent_color", Value::Str("blue".to_string())),
        ("night_shift_enabled", Value::Bool(true)),
        ("night_shift_temperature", Value::Int(4500)),
        ("reduce_motion", Value::Bool(false)),
        ("animation_speed", Value::Float(1.0)),
        ("glass_transparency", Value::Float(0.04)),
        ("glass_refraction", Value::Float(0.7)),
        ("border_size", Value::Int(0)),
    ] {
        appearance.push(key, value);
    }
    document.push("appearance", appearance);

    let mut bar = Section::new();
    bar.push("height", Value::Int(43));
    bar.push("spacing_scale", Value::Float(1.2));
    bar.push("clock_format", Value::Str("%a %d %b  %H:%M".to_string()));
    document.push("bar", bar);

    let mut pointer = Section::new();
    pointer.push("pointer_sensitivity", Value::Float(0.1 + 0.2));
    pointer.push("natural_scroll", Value::Bool(true));
    document.push("pointer", pointer);

    let mut skipped = Section::new();
    skipped.push(
        "nested",
        Value::Table(vec![("a".to_string(), Value::Int(1))]),
    );
    skipped.push("array", Value::Array(vec![Value::Int(1), Value::Int(2)]));
    skipped.push("kept", Value::Str("yes".to_string()));
    document.push("skipped", skipped);
    document
}

#[test]
fn the_document_is_byte_identical_to_the_python_emitter() {
    assert_eq!(dump_toml(&preferences_delta()).unwrap(), DOCUMENT);
}

/// `parsed[section][key]`, without the `Index` impl -- `indexing_slicing`
/// is denied workspace-wide and has no in-test exemption.
fn lookup<'a>(parsed: &'a toml::Table, section: &str, key: &str) -> Option<&'a toml::Value> {
    parsed.get(section)?.as_table()?.get(key)
}

#[test]
fn what_we_emit_parses_back_to_the_same_values() {
    let emitted = dump_toml(&preferences_delta()).unwrap();
    let parsed: toml::Table = emitted.parse().unwrap();
    let integer = |section, key| lookup(&parsed, section, key).and_then(toml::Value::as_integer);
    let float = |section, key| lookup(&parsed, section, key).and_then(toml::Value::as_float);
    assert_eq!(integer("schema", "preferences_version"), Some(5));
    assert_eq!(
        lookup(&parsed, "appearance", "wallpaper_dark").and_then(toml::Value::as_str),
        Some("/home/rizki/Pictures/it's \"dark\".png")
    );
    assert_eq!(float("appearance", "animation_speed"), Some(1.0));
    assert_eq!(
        lookup(&parsed, "appearance", "reduce_motion").and_then(toml::Value::as_bool),
        Some(false)
    );
    assert_eq!(float("pointer", "pointer_sensitivity"), Some(0.1 + 0.2));
    assert_eq!(integer("bar", "height"), Some(43));
    // The two containers were dropped; only `kept` survived the section.
    assert_eq!(
        parsed
            .get("skipped")
            .and_then(toml::Value::as_table)
            .map(toml::Table::len),
        Some(1)
    );
    // Emission has to be a fixed point, or the rewrite-only-on-change
    // check in compact_preferences_file() would rewrite on every load.
    assert_eq!(dump_toml(&preferences_delta()).unwrap(), emitted);
}

#[test]
fn strings_are_quoted_the_way_json_dumps_quotes_them() {
    let mut count = 0;
    for line in JSON_STRINGS.lines() {
        if line.starts_with('#') {
            continue;
        }
        let Some((hex, expected)) = line.split_once('\t') else {
            continue;
        };
        let bytes: Vec<u8> = (0..hex.len() / 2)
            .filter_map(|index| hex.get(index * 2..index * 2 + 2))
            .filter_map(|pair| u8::from_str_radix(pair, 16).ok())
            .collect();
        let text = String::from_utf8(bytes).unwrap();
        assert_eq!(json_string(&text), expected, "input {hex}");
        count += 1;
    }
    assert!(count >= 40, "corpus shrank to {count} strings");
}

#[test]
fn scalars_render_the_way_toml_value_renders_them() {
    assert_eq!(toml_value(&Value::Bool(true)).unwrap(), "true");
    assert_eq!(toml_value(&Value::Bool(false)).unwrap(), "false");
    assert_eq!(toml_value(&Value::Int(-1)).unwrap(), "-1");
    assert_eq!(toml_value(&Value::Float(43.0)).unwrap(), "43.0");
    assert_eq!(toml_value(&Value::Float(1e16)).unwrap(), "1e+16");
    assert_eq!(
        toml_value(&Value::Str("a\"b".to_string())).unwrap(),
        "\"a\\\"b\""
    );
}

#[test]
fn the_refusals_carry_the_python_message_text() {
    for value in [f64::NAN, f64::INFINITY, f64::NEG_INFINITY] {
        let error = toml_value(&Value::Float(value)).unwrap_err();
        assert_eq!(error.to_string(), "Non-finite numbers are not supported");
    }
    let array = Value::Array(vec![Value::Int(1), Value::Str("it's".to_string())]);
    assert_eq!(
        toml_value(&array).unwrap_err().to_string(),
        "Unsupported TOML value: [1, \"it's\"]"
    );
    let table = Value::Table(vec![("a".to_string(), Value::Float(1.0))]);
    assert_eq!(
        toml_value(&table).unwrap_err().to_string(),
        "Unsupported TOML value: {'a': 1.0}"
    );
}

#[test]
fn an_empty_document_is_a_single_newline() {
    assert_eq!(dump_toml(&Document::new()).unwrap(), "\n");
}

/// The empty-container special case: `json.dumps({"modules-left": []}, indent=2)` stays
/// inline as `[]` rather than opening onto an empty line.
#[test]
fn json_dumps_keeps_an_empty_container_inline() {
    let empty_object = Value::Table(vec![("modules-left".to_owned(), Value::Array(Vec::new()))]);
    assert_eq!(json_dumps(&empty_object, 2), "{\n  \"modules-left\": []\n}");
    assert_eq!(json_dumps(&Value::Array(Vec::new()), 2), "[]");
    assert_eq!(json_dumps(&Value::Table(Vec::new()), 2), "{}");
}

/// A table nesting an array of strings and a nested table, checked against
/// `json.dumps(value, indent=2)` run live over the same shape.
#[test]
fn json_dumps_matches_cpython_indent_two_over_a_nested_table() {
    let group = vec![
        (
            "orientation".to_owned(),
            Value::Str("horizontal".to_owned()),
        ),
        ("modules".to_owned(), Value::Array(Vec::new())),
    ];
    let nested = Value::Table(vec![
        ("height".to_owned(), Value::Int(43)),
        ("modules-center".to_owned(), Value::Array(Vec::new())),
        (
            "modules-right".to_owned(),
            Value::Array(vec![Value::Str("a".to_owned()), Value::Str("b".to_owned())]),
        ),
        ("group/x".to_owned(), Value::Table(group)),
    ]);
    assert_eq!(
        json_dumps(&nested, 2),
        concat!(
            "{\n",
            "  \"height\": 43,\n",
            "  \"modules-center\": [],\n",
            "  \"modules-right\": [\n",
            "    \"a\",\n",
            "    \"b\"\n",
            "  ],\n",
            "  \"group/x\": {\n",
            "    \"orientation\": \"horizontal\",\n",
            "    \"modules\": []\n",
            "  }\n",
            "}"
        )
    );
}

/// Three levels of nesting -- a table inside a table inside a table -- the shape
/// `waybar-clock.jsonc` actually writes.
#[test]
fn json_dumps_matches_cpython_indent_two_over_three_levels() {
    let clock = Value::Table(vec![(
        "clock".to_owned(),
        Value::Table(vec![
            (
                "format".to_owned(),
                Value::Str("{:%a %d %b  %H:%M}".to_owned()),
            ),
            (
                "calendar".to_owned(),
                Value::Table(vec![("iso8601".to_owned(), Value::Bool(true))]),
            ),
            ("locale".to_owned(), Value::Str("en_US.UTF-8".to_owned())),
        ]),
    )]);
    assert_eq!(
        json_dumps(&clock, 2),
        concat!(
            "{\n",
            "  \"clock\": {\n",
            "    \"format\": \"{:%a %d %b  %H:%M}\",\n",
            "    \"calendar\": {\n",
            "      \"iso8601\": true\n",
            "    },\n",
            "    \"locale\": \"en_US.UTF-8\"\n",
            "  }\n",
            "}"
        )
    );
}
