[package]
name = "garage-render"
version = "0.1.0"
edition = "2021"

[lib]
name = "garage_render"

[lints]
workspace = true

[dependencies]
garage-core = { path = "../garage-core" }
thiserror = "2.0.20"

[dev-dependencies]
serde_json = "1.0.145"
toml = { version = "1.1.4", features = ["preserve_order"] }
