//! `render_idle()`: `hypridle.conf` from the lock preferences, and nothing else.
//!
//! Its own function because it is its own entry point: `garage render-idle` is
//! `hypridle.service`'s `ExecStartPre`, and hypridle reads exactly this one file -- the
//! generated config names no include and sources nothing, so there is nothing else that unit
//! could need. Narrow on purpose. It used to run the full render there, which meant
//! restarting hypridle to pick up a new lock timeout also re-themed every toolkit, reloaded
//! the compositor and pushed `gsettings`, from inside the `set lock.*` that asked for the
//! restart.
//!
//! Not Lua, and not [`crate::lua`]: `hypridle.conf` is hypridle's own config syntax, and this
//! writes it through [`garage_core::fs::atomic::atomic_write`] -- a whole-file rewrite,
//! same as `preferences.toml` -- rather than through [`garage_core::fs::lua::write_lua`],
//! which is only for fragments `hyprland.lua` `dofile()`s.
//!
//! # The invariant this crate exists to hold
//!
//! Nothing here takes `PREFERENCES_LOCK`, and nothing here may ever be made to. `set lock.*`
//! holds that lock across a *synchronous* `systemctl restart hypridle.service`, whose
//! `ExecStartPre` re-enters this binary and runs this function: waiting on the lock here
//! would deadlock the setting against itself. [`crate::cx::RenderCx`]'s doc names this exact
//! call chain as invariant 4 -- the reason `garage-render` does not depend on `garage-prefs`
//! at all, so the lock this paragraph warns about cannot be reached from this function even
//! by accident.

use garage_core::fs::atomic::atomic_write;

use crate::cx::RenderCx;
use crate::error::RenderError;

/// `render_idle()` (garage:2352-2398): the shell of `hypridle.conf`, before any listener.
/// Ends with a blank line, matching the Python triple-quoted literal exactly -- the join
/// below adds the listeners after it.
fn general_block() -> String {
    let mut out = String::new();
    out.push_str("# Generated by garage. Edit preferences.toml instead.\n");
    out.push_str("general {\n");
    out.push_str("    lock_cmd = pidof hyprlock || ~/.config/hypr/scripts/garage-lock-session\n");
    out.push_str("    before_sleep_cmd = loginctl lock-session\n");
    out.push_str("    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ mode = \"on\" })'\n");
    out.push_str("}\n\n");
    out
}

/// `lock.lock_timeout`'s listener: `loginctl lock-session`.
fn lock_listener(timeout: i64) -> String {
    format!("listener {{\n    timeout = {timeout}\n    on-timeout = loginctl lock-session\n}}")
}

/// `lock.display_off_timeout`'s listener: DPMS off on timeout, back on on resume.
fn display_off_listener(timeout: i64) -> String {
    let mut out = format!("listener {{\n    timeout = {timeout}\n");
    out.push_str("    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ mode = \"off\" })'\n");
    out.push_str("    on-resume = hyprctl dispatch 'hl.dsp.dpms({ mode = \"on\" })'\n");
    out.push('}');
    out
}

/// `lock.suspend_timeout`'s listener: `systemctl suspend`.
fn suspend_listener(timeout: i64) -> String {
    format!("listener {{\n    timeout = {timeout}\n    on-timeout = systemctl suspend\n}}")
}

/// Write `hypridle.conf` from `[lock]` alone.
///
/// `lock_timeout`, `display_off_timeout` and `suspend_timeout` each become a listener only
/// when they are past zero -- zero means never, and hypridle would rather be told so than
/// be handed a listener with no timeout worth having. Every configured listener is joined
/// by a blank line, matching the Python's `"\n\n".join(listeners)` exactly, including the
/// case where none are configured at all (an empty join contributes nothing).
///
/// # Errors
///
/// [`RenderError::Atomic`] if `hypridle.conf` could not be written.
pub(crate) fn render_idle(cx: &RenderCx<'_>) -> Result<(), RenderError> {
    let lock = &cx.prefs().lock;
    let mut listeners = Vec::new();
    if lock.lock_timeout.get() > 0 {
        listeners.push(lock_listener(lock.lock_timeout.get()));
    }
    if lock.display_off_timeout.get() > 0 {
        listeners.push(display_off_listener(lock.display_off_timeout.get()));
    }
    if lock.suspend_timeout.get() > 0 {
        listeners.push(suspend_listener(lock.suspend_timeout.get()));
    }
    let mut idle = general_block();
    idle.push_str(&listeners.join("\n\n"));
    idle.push('\n');
    atomic_write(&cx.paths().fragments.hypridle, &idle)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use garage_core::paths::Paths;
    use garage_core::schema::defaults::Defaults;
    use garage_core::traits::{LuaCheckError, Monitor, MonitorError, MonitorSource};
    use std::collections::HashMap;
    use std::path::Path;

    use super::render_idle;
    use crate::cx::RenderCx;

    struct NoMonitors;
    impl MonitorSource for NoMonitors {
        fn monitors(&self) -> Result<Vec<Monitor>, MonitorError> {
            Ok(vec![])
        }
    }

    struct LuaAccepts;
    impl garage_core::traits::LuaSyntaxCheck for LuaAccepts {
        fn check(&self, _candidate: &Path) -> Result<(), LuaCheckError> {
            Ok(())
        }
    }

    fn paths(home: &Path) -> Paths {
        let env: HashMap<String, String> =
            [("HOME".to_owned(), home.to_string_lossy().into_owned())]
                .into_iter()
                .collect();
        Paths::from_env_map(&env)
    }

    #[test]
    fn the_default_desktop_writes_the_lock_and_display_off_listeners_but_not_suspend() {
        // Shipped defaults: lock_timeout = 600, display_off_timeout = 900, suspend_timeout
        // = 0 -- suspend is the one left off by default.
        let temp = std::env::temp_dir().join(format!("garage-idle-test-{}", std::process::id()));
        let paths = paths(&temp);
        let defaults = Defaults::compiled().expect("shipped defaults parse");
        let monitors = NoMonitors;
        let lua = LuaAccepts;
        let cx = RenderCx::new(defaults.values(), &paths, &monitors, &lua);

        render_idle(&cx).expect("render_idle writes hypridle.conf");

        let written =
            std::fs::read_to_string(&paths.fragments.hypridle).expect("hypridle.conf exists");
        assert!(written.starts_with("# Generated by garage. Edit preferences.toml instead.\n"));
        assert!(written.contains("timeout = 600\n    on-timeout = loginctl lock-session"));
        assert!(written.contains("timeout = 900\n    on-timeout = hyprctl dispatch"));
        assert!(!written.contains("systemctl suspend"));
        drop(std::fs::remove_dir_all(&temp));
    }

    // The all-zero (no listener) case, and every other lock timeout combination, is covered
    // by this task's byte-parity fixtures against the real Python backend (see
    // testdata/render_fixtures.json and the differential `render_idle` family), which is a
    // stronger check than a hand-built `Preferences` here -- and building one without a
    // `toml` dev-dependency this crate does not otherwise need is more machinery than a
    // second in-process case is worth.
}
