//! `gtk3_palette_css()` and `gtk4_palette_css()`: the palette as `@define-color` tokens.
//!
//! Two functions rather than one, because the two GTK generations do not carry the same
//! token set: GTK3 needs the pre-libadwaita `theme_*` tokens `adw-gtk3` still reads, and GTK4
//! needs the status pairs and the shade libadwaita draws with. Neither list is padded out to
//! the other -- a token a toolkit does not define today is a token its stylesheet is
//! currently getting from its own theme, and defining it here would silently restyle the
//! desktop.
//!
//! `gtk4_palette_css()` carries both schemes in one file, behind a `prefers-color-scheme`
//! media query, for a reason GTK3 does not share: GTK loads `gtk.css` once per process, so a
//! per-scheme `@import` would freeze the palette a running app launched with. libadwaita
//! re-evaluates the media query when the portal's `color-scheme` setting changes, which is
//! what `push_theme()` moves -- so a GTK4 app re-themes live and a GTK3 app does not, and
//! that difference is exactly why GTK3's file stays per-scheme while GTK4's does not.
//!
//! Both appearances' GTK3 files are written on every render, not just the resolved one, for
//! the reason `render_toolkits()`'s own doc gives: a render interrupted between the two would
//! otherwise leave a stylesheet importing a palette file that is not there, which GTK reads
//! as a silently dropped palette rather than an error anyone would see.
//!
//! Both return `String`, composed into files `render_toolkits()` writes rather than writing
//! one of their own.

use std::fmt::Write as _;

use garage_core::schema::enums::Scheme;

use crate::palette::table::{role, GTK3_TOKENS, GTK4_TOKENS};

/// The GTK3 palette `adw-gtk3` reads, as `@define-color` over the palette
/// (garage:3752-3757).
#[must_use]
pub(crate) fn gtk3_palette_css(scheme: Scheme) -> String {
    let mut tokens = String::new();
    for &(token, name) in GTK3_TOKENS {
        let _ = writeln!(tokens, "@define-color {token} {};", colour(scheme, name));
    }
    format!("/* Generated by garage: the {scheme} palette for GTK3. */\n{tokens}")
}

/// The GTK4/libadwaita palette, both appearances in one file (garage:3760-3780).
///
/// GTK loads `gtk.css` once per process, so a per-scheme import would freeze the palette a
/// running app launched with. libadwaita re-evaluates the media query when the portal's
/// color-scheme changes, which is what `push_theme()` moves.
#[must_use]
pub(crate) fn gtk4_palette_css() -> String {
    let mut light = String::new();
    let mut dark = String::new();
    for &(token, name) in GTK4_TOKENS {
        let _ = writeln!(light, "    --{token}: {};", colour(Scheme::Light, name));
        let _ = writeln!(dark, "        --{token}: {};", colour(Scheme::Dark, name));
    }
    format!(
        "/* Generated by garage: both appearances, so a running app follows the portal\n   \
         rather than freezing the palette it launched with. */\n:root {{\n{light}}}\n\n\
         @media (prefers-color-scheme: dark) {{\n    :root {{\n{dark}    }}\n}}\n"
    )
}

/// A token's colour. Every name in the two token tables is a `PALETTE` role by construction
/// -- `palette::parity`'s `gtk3_tokens_match_the_python_dump` and its GTK4 twin pin both
/// tables against the Python source -- so a miss would be a broken build, not something a
/// render could hit,
/// and the empty string it falls back to would be visible in the very first generated file.
fn colour(scheme: Scheme, name: &str) -> &'static str {
    role(scheme, name).unwrap_or_default()
}
