//! `rofi_palette_rasi()`: the launcher palette. `rasi` spells alpha as two hex digits
//! appended to the colour.
//!
//! A handful of roles handed straight through -- background, selection, border and two text
//! weights -- each with the alpha rofi's `rasi` syntax wants baked into the hex string itself
//! rather than a separate channel, and a `background-color` deliberately left transparent so
//! the base theme's own layer shows through. `@import "apple-base.rasi"` carries everything
//! that is not a colour, so this file's whole job is naming a few variables.
//!
//! Returns a `String`, written by `render_toolkits()` rather than by this module.

use garage_core::schema::enums::Scheme;

use crate::palette::table::role;

/// The launcher palette (garage:3783-3800). `rasi` spells alpha as two hex digits on the
/// colour.
#[must_use]
pub(crate) fn rofi_palette_rasi(scheme: Scheme) -> String {
    let colour = |name: &str| role(scheme, name).unwrap_or_default();
    format!(
        "/* Generated by garage: the {scheme} palette for rofi. */
* {{
    background: {bg_raised}e6;
    selection: {accent}d9;
    border-color: {on_bg}20;
    foreground: {fg}ff;
    foreground-strong: {fg_bright}ff;
    foreground-muted: {fg_muted}ff;
    background-color: transparent;
    text-color: @foreground;
    font: \"Plus Jakarta Sans 12\";
}}

@import \"apple-base.rasi\"
",
        bg_raised = colour("bg_raised"),
        accent = colour("accent"),
        on_bg = colour("on_bg"),
        fg = colour("fg"),
        fg_bright = colour("fg_bright"),
        fg_muted = colour("fg_muted"),
    )
}
