//! `swayosd_palette_css()`: the volume/brightness OSD palette, as GTK named colours.
//!
//! Six roles -- the OSD's edge, body, foreground, muted foreground, track and fill -- each a
//! `@define-color`, imported by a small per-scheme `style.css` alongside `swayosd-base.css`.
//! The OSD is the one surface that reads its own composited body colour directly rather than
//! through a toolkit's own theming layer, which is why it gets a palette writer of its own
//! rather than sharing GTK's.
//!
//! Returns a `String`, written by `render_toolkits()` rather than by this module.

use garage_core::schema::enums::Scheme;

use crate::palette::table::role;

/// The volume/brightness OSD palette, as GTK named colours (garage:3803-3815).
#[must_use]
pub(crate) fn swayosd_palette_css(scheme: Scheme) -> String {
    let colour = |name: &str| role(scheme, name).unwrap_or_default();
    format!(
        "/* Generated by garage: the {scheme} palette for swayosd. */
@define-color osd_edge {edge};
@define-color osd_bg {bg};
@define-color osd_fg {fg};
@define-color osd_fg_muted {fg_muted};
@define-color osd_track {track};
@define-color osd_fill {fill};

@import \"swayosd-base.css\";
",
        edge = colour("edge"),
        bg = colour("osd_bg"),
        fg = colour("osd_fg"),
        fg_muted = colour("osd_fg_muted"),
        track = colour("osd_track"),
        fill = colour("osd_fill"),
    )
}
