//! `waybar_style_css()`: the bar's whole generated stylesheet -- colours, the base import,
//! the scaled spacing.
//!
//! Its own function, and not just tidiness: `bar.padding_scale` is a slider, so `set` fires
//! one of these per notch, and the narrow apply-side `render_bar_style()` writes this one
//! file alone rather than dragging the other twenty toolkit configs
//! [`crate::palette::toolkits`] owns along with it.
//!
//! Waybar uses Hyprland's native layer blur, with a light or dark translucent tint selected
//! from the resolved scheme -- [`crate::bar::style`]'s `bar_background()` is where that tint
//! is picked. The bar's foreground is the tint direction itself, `on_bg` from
//! [`crate::palette::table`] -- white over the dark glass, black over the light -- because it
//! is read against the desktop rather than against a surface. The workspace dot's three
//! opacity states (idle, hover, active) are the one place this file spells out an alpha ramp
//! of its own rather than reading one from the palette, because none of the three is a role
//! any other surface needs.
//!
//! Composed from [`crate::bar::style`]'s `bar_background()` and [`crate::bar::spacing`]'s
//! `waybar_spacing_css()`, appended after the generated colour block and the `@import` of
//! `waybar-base.css`.
//!
//! Doc-only: returns a `String`, written both by `render_toolkits()` (every render) and by
//! `garage-apply`'s narrow `render_bar_style()` (a padding or background change alone).
//!
//! # Why this one is not a template
//!
//! Every other file `render_toolkits()` writes has had its text moved into
//! [`crate::template`]'s `templates/` directory. This one keeps its literal, for two
//! reasons that both come out of the same fact -- it is the only generated file whose
//! contents read a *preference* rather than only the palette:
//!
//! * Most of it is computed. `waybar_spacing_css()` derives every rule below the `@import`
//!   from `bar.padding_scale`, `bar.height` and the widget list -- there is no fixed prose
//!   in that half at all, and a template for it would be one placeholder holding a whole
//!   stylesheet.
//! * Its entry point is shared. `waybar_style_css()` is public because `garage-apply`'s
//!   `render_bar_style()` calls it for a single slider notch, and it is handed a `Scheme`
//!   and a `Preferences` -- no [`Paths`](garage_core::paths::Paths), which is what a
//!   template is loaded from. Templating the sixteen `@define-color` lines above the
//!   `@import` would change that signature for every caller, and put a directory read on
//!   the path a slider drags through.
//!
//! The sixteen colour lines are fixed text and would template cleanly on their own. If
//! this file is ever split so the colour block has an entry point of its own, that block
//! is the piece to move.

use garage_core::schema::enums::Scheme;
use garage_core::schema::Preferences;

use crate::bar::spacing::waybar_spacing_css;
use crate::bar::style::bar_background;
use crate::palette::table::role;

/// `rgb_parts()` (garage:3730-3733): `r, g, b` from an opaque `#rrggbb`, for a CSS function
/// that wants channels rather than a hex triplet.
///
/// Every role this is called with -- `bar_dot` -- is opaque in both schemes by construction,
/// the same guarantee [`crate::theme::opaque_role`]'s callers rely on, so the fallback of
/// `"0, 0, 0"` for a malformed input is unreachable rather than a case a caller here can hit.
fn rgb_parts(color: &str) -> String {
    let digits = color.strip_prefix('#').unwrap_or(color);
    let channel = |at: usize| -> u8 {
        digits
            .get(at..at + 2)
            .and_then(|pair| u8::from_str_radix(pair, 16).ok())
            .unwrap_or(0)
    };
    format!("{}, {}, {}", channel(0), channel(2), channel(4))
}

/// A `PALETTE` role for one scheme, `""` if somehow absent. Every name below is one of the
/// table's fixed roles -- `palette::parity::palette_matches_the_python_dump` pins the whole
/// table against the Python source -- so the fallback is unreachable in practice.
fn colour(scheme: Scheme, name: &str) -> &'static str {
    role(scheme, name).unwrap_or_default()
}

/// The bar's whole generated stylesheet: colours, the import, the overrides
/// (`waybar_style_css()`, garage:3984-4021).
#[must_use]
pub fn waybar_style_css(scheme: Scheme, prefs: &Preferences) -> String {
    let bar_fg = colour(scheme, "on_bg");
    let dot = rgb_parts(colour(scheme, "bar_dot"));
    format!(
        "/* Generated by garage. */\n\
         @define-color bar_bg {bar_bg};\n\
         @define-color bar_edge {bar_edge};\n\
         @define-color bar_sheen {bar_sheen};\n\
         @define-color bar_fg {bar_fg};\n\
         @define-color menu_fg {bar_fg};\n\
         @define-color module_fg {bar_fg};\n\
         @define-color module_fg_hover {bar_fg};\n\
         @define-color module_hover_bg alpha({bar_fg}, 0.12);\n\
         @define-color module_press_bg alpha({bar_fg}, 0.22);\n\
         @define-color module_fg_muted alpha({bar_fg}, 0.55);\n\
         @define-color dot_idle rgba({dot}, 0.45);\n\
         @define-color dot_hover rgba({dot}, 0.65);\n\
         @define-color dot_active rgba({dot}, 0.95);\n\
         @define-color urgent {urgent};\n\
         @define-color tooltip_bg {tooltip_bg};\n\
         @define-color tooltip_fg {tooltip_fg};\n\
         \n\
         @import \"waybar-base.css\";\n\
         \n\
         {spacing}",
        bar_bg = bar_background(scheme, prefs),
        bar_edge = colour(scheme, "bar_edge"),
        bar_sheen = colour(scheme, "bar_sheen"),
        urgent = colour(scheme, "urgent"),
        tooltip_bg = colour(scheme, "tooltip_bg"),
        tooltip_fg = colour(scheme, "fg_strong"),
        spacing = waybar_spacing_css(prefs),
    )
}

#[cfg(test)]
mod tests {
    use garage_core::schema::defaults::Defaults;
    use garage_core::schema::enums::Scheme;

    use super::{rgb_parts, waybar_style_css};

    #[test]
    fn rgb_parts_reads_decimal_channels_from_an_opaque_hex() {
        assert_eq!(rgb_parts("#0a84ff"), "10, 132, 255");
        assert_eq!(rgb_parts("#ffffff"), "255, 255, 255");
        assert_eq!(rgb_parts("#000000"), "0, 0, 0");
    }

    /// The former backend's `waybar_style_css("dark"|"light", FALLBACK_DEFAULTS)` output,
    /// captured during the Rust port. The
    /// same fixture also lives in `testdata/theme_fixtures.json`'s `"toolkits"` section, which
    /// `render_toolkits()`'s own byte-parity test reads.
    const DARK_FIXTURE: &str = include_str!("../../testdata/waybar_style_dark.css");
    const LIGHT_FIXTURE: &str = include_str!("../../testdata/waybar_style_light.css");

    #[test]
    fn matches_the_python_backend_byte_for_byte_on_the_shipped_defaults() {
        let defaults = Defaults::compiled().expect("shipped defaults parse");
        assert_eq!(
            waybar_style_css(Scheme::Dark, defaults.values()),
            DARK_FIXTURE
        );
        assert_eq!(
            waybar_style_css(Scheme::Light, defaults.values()),
            LIGHT_FIXTURE
        );
    }
}
