//! `render_preferences()`: the shared fragment most appearance and input keys land in.
//!
//! One `hyprland.lua` fragment carrying three separate `hl.config()` calls: the whole
//! `[input]` section, then the theme-resolved decoration -- corner rounding, the group and
//! border colours, the material's core options -- then, guarded on `GLASS_AVAILABLE` and
//! `HYPREXPO_AVAILABLE`, the two plugins' own rounding. Guarded because setting a plugin
//! keyword for a plugin that failed to load is a config error, not a no-op. Those two guard
//! names are not preferences: they are Lua globals `config/*.lua` sets when a plugin loads,
//! so they are emitted here as literal text and never touched by Rust.
//!
//! The glass values matter here as much as the colours: the corner rings are a white inner
//! highlight over a dark outer border, which inverts on a light desktop, and a near-black
//! tint would darken it rather than lighten it. `render_preferences()` is also the one
//! renderer that writes the material marker ([`crate::theme`] does not) so the shell has
//! something to read before it first draws, the same way the corner radius marker is
//! published from more than one place.
//!
//! Ends by rendering the idle fragment too -- in the Python, `render_preferences()` is the
//! last stop before `render_idle()` on every route that touches `[input]`, because Reduce
//! Motion and the lock timeouts live in neighbouring parts of the same generated
//! `hyprland.lua` include chain. That call has to land on the same path `garage
//! render-idle`'s re-entrant restart takes, which is why [`crate::idle`] carries its own
//! invariant about never taking the preferences lock rather than inheriting one from here.
//!
//! # Theme resolution
//!
//! `border_general()`, the group border colours, the glass tint and the decoration shadow all
//! need a resolved light/dark [`Scheme`], which is [`crate::theme::resolve_theme`]'s answer
//! and is read from it directly. This file carried a stand-in for that while `crate::theme`
//! was still a stub -- one whose `"auto"` arm could not read the wall clock and fell back to
//! `Scheme::Dark` -- and the stand-in and its deviation are both gone: an `auto` desktop now
//! renders the borders, tint and shadow of whichever appearance the schedule actually puts on
//! screen, the same as every other palette consumer.

use std::fmt::Write as _;

use garage_core::fs::lua::write_lua;
use garage_core::fs::marker::write_marker;
use garage_core::schema::enums::Scheme;
use garage_core::schema::Preferences;

use crate::cx::RenderCx;
use crate::error::RenderError;
use crate::idle::render_idle;
use crate::lua::emit::{
    border_general, corner_rounding, glass_options, lua_pairs, material_decoration, motion_lua,
    python_g_format, CORNER_POWER,
};
use crate::lua::escape::lua_string;
use crate::palette::accents::border_colors;
use crate::palette::table::role as palette_role;
use crate::theme::resolve_theme;

/// Write the shared `hyprland.lua` fragment: `[input]`, the theme-resolved decoration, and
/// the two plugin blocks. Then the material marker, and `hypridle.conf` through
/// [`render_idle`], exactly as the Python's `render_preferences()` ends by calling
/// `render_idle()`.
///
/// # Errors
///
/// [`RenderError::Marker`] if the material marker could not be written,
/// [`RenderError::Lua`] if the generated fragment could not be staged, checked or installed,
/// or whatever [`render_idle`] returns.
pub(crate) fn render_preferences(cx: &RenderCx<'_>) -> Result<(), RenderError> {
    let prefs = cx.prefs();
    let paths = cx.paths();

    // Published here as well as from apply_glass so the marker exists before the shell
    // first reads it, the same way the corner radius is handled.
    write_marker(
        &paths.markers.material,
        &format!("{}\n", prefs.appearance.glass_mode.as_str()),
    )?;

    let theme = resolve(prefs);
    let mut lua = input_block(prefs);
    lua.push_str(&decoration_block(prefs, &theme));
    lua.push_str(&plugin_block(prefs, &theme));
    lua.push('\n');
    lua.push_str(&motion_lua(prefs));

    write_lua(&paths.fragments.hyprland, &lua, cx.lua())?;
    render_idle(cx)
}

/// The `[input]` `hl.config()` call, byte-identical to the Python's f-string (garage:2219-
/// 2237, `render_preferences()`'s first third).
fn input_block(prefs: &Preferences) -> String {
    let inputs = &prefs.input;
    let mut out = String::from("-- Generated by garage. Edit preferences.toml instead.\n");
    out.push_str("hl.config({\n    input = {\n");
    let sensitivity = python_g_format(inputs.pointer_sensitivity.get());
    let _ = writeln!(out, "        sensitivity = {sensitivity},");
    let accel = lua_string(inputs.accel_profile.as_str());
    let _ = writeln!(out, "        accel_profile = {accel},");
    let _ = writeln!(
        out,
        "        natural_scroll = {},",
        inputs.natural_scroll.get()
    );
    let keyboard_layout = lua_string(inputs.keyboard_layout.as_str());
    let _ = writeln!(out, "        kb_layout = {keyboard_layout},");
    let _ = writeln!(out, "        repeat_rate = {},", inputs.repeat_rate.get());
    let _ = writeln!(out, "        repeat_delay = {},", inputs.repeat_delay.get());
    out.push_str("        touchpad = {\n");
    let _ = writeln!(
        out,
        "            tap_to_click = {},",
        inputs.touchpad_tap_to_click.get()
    );
    let _ = writeln!(
        out,
        "            natural_scroll = {},",
        inputs.touchpad_natural_scroll.get()
    );
    let _ = writeln!(
        out,
        "            disable_while_typing = {},",
        inputs.touchpad_disable_while_typing.get()
    );
    out.push_str("        },\n    },\n})\n");
    out
}

/// A `PALETTE` role that must be present for both schemes, the way `opaque()` reads one.
/// `border_locked`, `body_opaque` and `shadow_base` are three of `PALETTE`'s fixed roles,
/// present for both schemes by construction --
/// `palette::table::parity::every_role_is_defined_for_both_schemes` pins this against the
/// Python source, the same guarantee [`crate::palette::accents::border_colors`] leans on.
#[allow(clippy::expect_used)]
fn opaque_role(scheme: Scheme, name: &str) -> &'static str {
    palette_role(scheme, name).expect("name is one of PALETTE's fixed roles")
}

/// `opaque(scheme, role).lstrip("#")` wrapped in hyprlang's `rgba(rrggbbaa)` spelling
/// (garage:2249-2250's `hypr()` closure).
fn rgba(hex: &str, alpha: &str) -> String {
    let stripped = hex.trim_start_matches('#');
    format!("rgba({stripped}{alpha})")
}

/// The material's own weights, resolved once per scheme (garage:2258-2280's two branches,
/// identical apart from the shadow alpha).
struct MaterialColors {
    tint: String,
    tint_opacity: f64,
    saturation: f64,
    frame_highlight: f64,
    frame_border: f64,
    dispersion: f64,
    shadow: String,
    shadow_inactive: String,
    dim_strength: f64,
}

fn material_colors(scheme: Scheme) -> MaterialColors {
    let body_opaque = opaque_role(scheme, "body_opaque");
    // A drop shadow is black in both appearances (PALETTE's shadow_base); only the alpha
    // the two branches pick differs.
    let shadow_base = opaque_role(scheme, "shadow_base");
    let (shadow_alpha, shadow_alpha_inactive) = match scheme {
        Scheme::Light => ("26", "14"),
        Scheme::Dark => ("66", "40"),
    };
    MaterialColors {
        tint: rgba(body_opaque, "ff"),
        tint_opacity: 0.20,
        saturation: 0.5,
        frame_highlight: 0.10,
        frame_border: 0.05,
        dispersion: 0.0,
        shadow: rgba(shadow_base, shadow_alpha),
        shadow_inactive: rgba(shadow_base, shadow_alpha_inactive),
        dim_strength: 0.08,
    }
}

/// Everything the decoration and plugin blocks need, resolved once.
struct ResolvedTheme {
    rounding: u16,
    group_active: String,
    group_inactive: String,
    group_locked: String,
    material: MaterialColors,
}

fn resolve(prefs: &Preferences) -> ResolvedTheme {
    let scheme = resolve_theme(prefs);
    let (group_active, group_inactive) = border_colors(scheme);
    let group_locked = rgba(opaque_role(scheme, "border_locked"), "ff");
    ResolvedTheme {
        rounding: corner_rounding(prefs),
        group_active,
        group_inactive,
        group_locked,
        material: material_colors(scheme),
    }
}

/// The group and decoration `hl.config()` call, byte-identical to the Python's f-string
/// (garage:2277-2312).
fn decoration_block(prefs: &Preferences, theme: &ResolvedTheme) -> String {
    let border = border_general(
        prefs.appearance.border_size.get(),
        &theme.group_active,
        &theme.group_inactive,
    );
    let material = lua_pairs(&material_decoration(prefs), ",\n        ");
    let mut out = String::from("\nhl.config({\n");
    let _ = writeln!(out, "    general = {{ {border} }},");
    out.push_str("    group = {\n        col = {\n");
    let (active, inactive, locked) = (
        &theme.group_active,
        &theme.group_inactive,
        &theme.group_locked,
    );
    let _ = writeln!(out, "            border_active = \"{active}\",");
    let _ = writeln!(out, "            border_inactive = \"{inactive}\",");
    let _ = writeln!(out, "            border_locked_active = \"{locked}\",");
    let _ = writeln!(out, "            border_locked_inactive = \"{inactive}\",");
    out.push_str("        },\n        groupbar = {\n            col = {\n");
    let _ = writeln!(out, "                active = \"{active}\",");
    let _ = writeln!(out, "                inactive = \"{inactive}\",");
    let _ = writeln!(out, "                locked_active = \"{locked}\",");
    let _ = writeln!(out, "                locked_inactive = \"{inactive}\",");
    out.push_str("            },\n        },\n    },\n    decoration = {\n");
    let dim_strength = python_g_format(theme.material.dim_strength);
    let _ = writeln!(out, "        dim_strength = {dim_strength},");
    let _ = writeln!(out, "        rounding = {},", theme.rounding);
    let rounding_power = python_g_format(CORNER_POWER);
    let _ = writeln!(out, "        rounding_power = {rounding_power},");
    let _ = writeln!(out, "        {material},");
    out.push_str("        shadow = {\n");
    let _ = writeln!(out, "            color = \"{}\",", theme.material.shadow);
    let _ = writeln!(
        out,
        "            color_inactive = \"{}\",",
        theme.material.shadow_inactive
    );
    out.push_str("        },\n    },\n})\n");
    out
}

/// The two plugin-guarded `hl.config()` calls, byte-identical to the Python's f-string
/// (garage:2315-2350). `GLASS_AVAILABLE` and `HYPREXPO_AVAILABLE` are Lua globals, emitted
/// as literal text -- see the module docs.
fn plugin_block(prefs: &Preferences, theme: &ResolvedTheme) -> String {
    let options = lua_pairs(&glass_options(prefs), ",\n                ");
    let mut out = String::from(
        "\nif GLASS_AVAILABLE then\n    hl.config({\n        plugin = {\n            kinetik_glass = {\n",
    );
    let _ = writeln!(out, "                {options},");
    let _ = writeln!(out, "                layer_rounding = {},", theme.rounding);
    let corner_power = python_g_format(CORNER_POWER);
    let _ = writeln!(out, "                corner_power = {corner_power},");
    let _ = writeln!(out, "                tint = \"{}\",", theme.material.tint);
    let tint_opacity = python_g_format(theme.material.tint_opacity);
    let _ = writeln!(out, "                tint_opacity = {tint_opacity},");
    let frame_highlight = python_g_format(theme.material.frame_highlight);
    let _ = writeln!(
        out,
        "                frame_highlight_opacity = {frame_highlight},"
    );
    let frame_border = python_g_format(theme.material.frame_border);
    let _ = writeln!(
        out,
        "                frame_border_opacity = {frame_border},"
    );
    let dispersion = python_g_format(theme.material.dispersion);
    let _ = writeln!(out, "                dispersion = {dispersion},");
    let saturation = python_g_format(theme.material.saturation);
    let _ = writeln!(out, "                saturation = {saturation},");
    out.push_str("            },\n        },\n    })\nend\n\n");
    out.push_str("if HYPREXPO_AVAILABLE then\n    hl.config({\n        plugin = {\n            hyprexpo = {\n");
    let _ = writeln!(out, "                tile_rounding = {},", theme.rounding);
    let _ = writeln!(out, "                tile_rounding_power = {corner_power},");
    out.push_str("            },\n        },\n    })\nend\n");
    out
}

#[cfg(test)]
mod tests {
    use garage_core::paths::Paths;
    use garage_core::schema::defaults::Defaults;
    use garage_core::traits::{LuaCheckError, Monitor, MonitorError, MonitorSource};
    use std::collections::HashMap;
    use std::path::Path;

    use super::render_preferences;
    use crate::cx::RenderCx;

    struct NoMonitors;
    impl MonitorSource for NoMonitors {
        fn monitors(&self) -> Result<Vec<Monitor>, MonitorError> {
            Ok(vec![])
        }
    }

    struct LuaAccepts;
    impl garage_core::traits::LuaSyntaxCheck for LuaAccepts {
        fn check(&self, _candidate: &Path) -> Result<(), LuaCheckError> {
            Ok(())
        }
    }

    struct LuaRejects;
    impl garage_core::traits::LuaSyntaxCheck for LuaRejects {
        fn check(&self, _candidate: &Path) -> Result<(), LuaCheckError> {
            Err(LuaCheckError {
                detail: "line 1: nope".to_owned(),
            })
        }
    }

    fn paths(home: &Path) -> Paths {
        let env: HashMap<String, String> =
            [("HOME".to_owned(), home.to_string_lossy().into_owned())]
                .into_iter()
                .collect();
        Paths::from_env_map(&env)
    }

    #[test]
    fn the_default_desktop_writes_a_fragment_hypridle_and_the_material_marker() {
        let temp = std::env::temp_dir().join(format!("garage-prefs-test-{}", std::process::id()));
        let paths = paths(&temp);
        let defaults = Defaults::compiled().expect("shipped defaults parse");
        let monitors = NoMonitors;
        let lua = LuaAccepts;
        let cx = RenderCx::new(defaults.values(), &paths, &monitors, &lua);

        render_preferences(&cx).expect("render_preferences succeeds against a clean scratch");

        let fragment =
            std::fs::read_to_string(&paths.fragments.hyprland).expect("fragment written");
        assert!(fragment.starts_with("-- Generated by garage. Edit preferences.toml instead."));
        assert!(fragment.contains("if GLASS_AVAILABLE then"));
        assert!(fragment.contains("if HYPREXPO_AVAILABLE then"));
        assert!(std::fs::metadata(&paths.fragments.hypridle).is_ok());
        let material = std::fs::read_to_string(&paths.markers.material).expect("marker written");
        assert_eq!(material, "liquid\n");
        drop(std::fs::remove_dir_all(&temp));
    }

    #[test]
    fn a_lua_rejection_surfaces_as_a_lua_error_and_writes_no_fragment() {
        let temp =
            std::env::temp_dir().join(format!("garage-prefs-reject-test-{}", std::process::id()));
        let paths = paths(&temp);
        let defaults = Defaults::compiled().expect("shipped defaults parse");
        let monitors = NoMonitors;
        let lua = LuaRejects;
        let cx = RenderCx::new(defaults.values(), &paths, &monitors, &lua);

        let error = render_preferences(&cx).expect_err("a rejecting luac must fail the render");
        assert!(matches!(error, crate::error::RenderError::Lua(_)));
        assert!(!paths.fragments.hyprland.exists());
        drop(std::fs::remove_dir_all(&temp));
    }
}
