//! `render_region()`: publish the locale override and the bar's clock, as generated fragments.
//!
//! Both belong in files this crate cannot write directly: `~/.config/uwsm/env` and waybar's
//! `config.jsonc` are stow symlinks into the dotfiles repo, and rewriting either on a
//! settings change would edit a tracked file. So each one reaches in from its own side
//! instead -- the env file sources a generated `locale.env`, `config.jsonc` includes a
//! generated `waybar-clock.jsonc` -- and only the generated halves move.
//!
//! No export at all for an empty locale override, rather than exporting the system value:
//! the point of an empty override is that the session is left to resolve `LANG` the way it
//! would with the file absent, and exporting the resolved value would pin it instead.
//!
//! The bar clock is the one part of a locale choice that can be honoured before the next
//! login: its `std::locale` is handed in explicitly rather than read from the process
//! environment, so the weekday and month names move immediately rather than waiting for a
//! relaunch.

use garage_core::fs::atomic::atomic_write;
use garage_core::schema::enums::{DateFormat, FirstDayOfWeek, TimeFormat};
use garage_core::schema::Preferences;
use garage_core::shlex::shlex_quote;
use garage_core::toml_emit::{json_dumps, Value};

use crate::cx::RenderCx;
use crate::error::RenderError;

/// `DATE_FORMATS` (garage:320): the `strftime` date half, per `region.date_format`.
const fn date_format(format: DateFormat) -> &'static str {
    match format {
        DateFormat::Dmy => "%a %d %b",
        DateFormat::Mdy => "%a %b %d",
        DateFormat::Iso => "%a %Y-%m-%d",
    }
}

/// `TIME_FORMATS` (garage:319): the `strftime` time half, per `region.time_format`.
const fn time_format(format: TimeFormat) -> &'static str {
    match format {
        TimeFormat::Twelve => "%I:%M %p",
        TimeFormat::TwentyFour => "%H:%M",
    }
}

/// `FIRST_WEEKDAYS` (garage:323): waybar's calendar has no first-weekday option of its own,
/// only the ISO 8601 switch, which is defined as weeks beginning on Monday.
const fn first_weekday_is_monday(first_day: FirstDayOfWeek) -> bool {
    match first_day {
        FirstDayOfWeek::Sunday => false,
        FirstDayOfWeek::Monday => true,
    }
}

/// `clock_format()` (garage:4518-4521): the bar clock's `strftime` string, date part then
/// time part, two spaces apart.
fn clock_format(prefs: &Preferences) -> String {
    let region = &prefs.region;
    format!(
        "{}  {}",
        date_format(region.date_format),
        time_format(region.time_format)
    )
}

/// `locale.env`'s whole body: the header comment, then an `export LANG=...` line only when
/// the override is not empty.
fn locale_env(prefs: &Preferences) -> String {
    let header = "# Generated by garage. Sourced from ~/.config/uwsm/env.\n";
    let locale = prefs.region.locale.as_str();
    if locale.is_empty() {
        header.to_owned()
    } else {
        format!("{header}export LANG={}\n", shlex_quote(locale))
    }
}

/// `waybar-clock.jsonc`'s whole body: the clock's `strftime` format wrapped for
/// `{fmt}`-style interpolation, the calendar's first-weekday switch, and the locale itself
/// when there is one to hand the formatter explicitly.
fn waybar_clock_json(prefs: &Preferences) -> String {
    let region = &prefs.region;
    let mut clock: Vec<(String, Value)> = vec![
        (
            "format".to_owned(),
            Value::Str(format!("{{:{}}}", clock_format(prefs))),
        ),
        (
            "calendar".to_owned(),
            Value::Table(vec![(
                "iso8601".to_owned(),
                Value::Bool(first_weekday_is_monday(region.first_day_of_week)),
            )]),
        ),
    ];
    let locale = region.locale.as_str();
    if !locale.is_empty() {
        clock.push(("locale".to_owned(), Value::Str(locale.to_owned())));
    }
    let document = Value::Table(vec![("clock".to_owned(), Value::Table(clock))]);
    format!("{}\n", json_dumps(&document, 2))
}

/// Write the locale override and the bar's clock format (`render_region()`, garage:4525-4552).
///
/// # Errors
///
/// [`RenderError::Atomic`] if either fragment could not be replaced.
pub(crate) fn render_region(cx: &RenderCx<'_>) -> Result<(), RenderError> {
    atomic_write(&cx.paths().fragments.locale_env, &locale_env(cx.prefs()))?;
    atomic_write(
        &cx.paths().fragments.waybar_clock,
        &waybar_clock_json(cx.prefs()),
    )?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use std::collections::HashMap;
    use std::path::Path;

    use garage_core::paths::Paths;
    use garage_core::schema::defaults::Defaults;
    use garage_core::schema::notes::Notes;
    use garage_core::schema::Preferences;
    use garage_core::traits::{
        LuaCheckError, LuaSyntaxCheck, Monitor, MonitorError, MonitorSource,
    };

    use super::render_region;
    use crate::cx::RenderCx;

    fn prefs_from(departures: &str) -> Preferences {
        let table: toml::Table = departures.parse().expect("fixture toml parses");
        let defaults = Defaults::compiled().expect("shipped defaults parse");
        let mut notes = Notes::new();
        Preferences::coerce_from(&table, &defaults, &mut notes)
    }

    struct NoMonitors;
    impl MonitorSource for NoMonitors {
        fn monitors(&self) -> Result<Vec<Monitor>, MonitorError> {
            Ok(vec![])
        }
    }

    struct LuaAccepts;
    impl LuaSyntaxCheck for LuaAccepts {
        fn check(&self, _candidate: &Path) -> Result<(), LuaCheckError> {
            Ok(())
        }
    }

    fn scratch_paths(label: &str) -> Paths {
        let home = std::env::temp_dir().join(format!(
            "garage-render-region-{label}-{}-{:?}",
            std::process::id(),
            std::thread::current().id()
        ));
        let env: HashMap<String, String> =
            [("HOME".to_owned(), home.to_string_lossy().into_owned())]
                .into_iter()
                .collect();
        Paths::from_env_map(&env)
    }

    /// `desktop/.local/bin/garage`'s own `render_region(FALLBACK_DEFAULTS)`, captured with
    /// `tests/harness.py` -- the shipped defaults carry no locale override.
    #[test]
    fn matches_the_python_backend_with_no_locale_override() {
        let prefs = prefs_from("");
        let paths = scratch_paths("defaults");
        let monitors = NoMonitors;
        let lua = LuaAccepts;
        let cx = RenderCx::new(&prefs, &paths, &monitors, &lua);
        render_region(&cx).expect("render_region succeeds on a clean scratch");

        let locale_env =
            std::fs::read_to_string(&paths.fragments.locale_env).expect("locale.env was written");
        assert_eq!(
            locale_env,
            "# Generated by garage. Sourced from ~/.config/uwsm/env.\n"
        );
        let clock = std::fs::read_to_string(&paths.fragments.waybar_clock)
            .expect("waybar-clock.jsonc was written");
        assert_eq!(
            clock,
            "{\n  \"clock\": {\n    \"format\": \"{:%a %d %b  %H:%M}\",\n    \"calendar\": {\n      \"iso8601\": false\n    }\n  }\n}\n"
        );
        drop(std::fs::remove_dir_all(&paths.home));
    }

    /// A locale override, an ISO date, a 12-hour clock and a Monday-first calendar --
    /// captured the same way, so the export line, the format string and the `locale` key
    /// added to the clock object are all pinned against the real backend.
    #[test]
    fn matches_the_python_backend_with_a_locale_override() {
        let prefs = prefs_from(
            "[region]\nlocale = \"en_US.UTF-8\"\ndate_format = \"iso\"\ntime_format = \"12\"\n\
             first_day_of_week = \"monday\"\n",
        );
        let paths = scratch_paths("locale");
        let monitors = NoMonitors;
        let lua = LuaAccepts;
        let cx = RenderCx::new(&prefs, &paths, &monitors, &lua);
        render_region(&cx).expect("render_region succeeds on a clean scratch");

        let locale_env =
            std::fs::read_to_string(&paths.fragments.locale_env).expect("locale.env was written");
        assert_eq!(
            locale_env,
            "# Generated by garage. Sourced from ~/.config/uwsm/env.\nexport LANG=en_US.UTF-8\n"
        );
        let clock = std::fs::read_to_string(&paths.fragments.waybar_clock)
            .expect("waybar-clock.jsonc was written");
        assert_eq!(
            clock,
            "{\n  \"clock\": {\n    \"format\": \"{:%a %Y-%m-%d  %I:%M %p}\",\n    \"calendar\": {\n      \"iso8601\": true\n    },\n    \"locale\": \"en_US.UTF-8\"\n  }\n}\n"
        );
        drop(std::fs::remove_dir_all(&paths.home));
    }
}
