//! `render_wallpaper()`: the generated `hyprpaper.conf`, and what it resolves the picture from.
//!
//! hyprpaper 0.8.4 reads `fit_mode` from its config file, and only at startup: its IPC
//! exposes `wallpaper` and `listactive` alone, there is no reload request and no signal
//! handler. A changed file is therefore exactly the set of cases that need the service
//! restarted, which is why the real `render_wallpaper()` reports whether it changed instead
//! of restarting anything itself -- the restart decision belongs to the apply side, which is
//! the caller that knows whether this is the only thing that moved.
//!
//! The path this fragment names is always the `current` symlink, never a resolved target,
//! because that is what a fresh session boots from; a live path change goes over hyprpaper's
//! IPC instead, on the apply side, and never touches this file at all.
//!
//! `wallpaper_target()` is the resolver behind it: a colour is an image too, since hyprpaper
//! has no colour mode of its own, so a chosen swatch is rendered to a solid PNG named after
//! it and cached under the wallpaper directory. An appearance that has never been given a
//! picture falls back to whatever `current` already points at, which keeps the desktop it
//! has rather than blanking it -- and only a first session, before any wallpaper has ever
//! been chosen, resolves to nothing at all.
//!
//! Not reached through [`RenderStep`](garage_core::schema::routes::RenderStep): none of the
//! three wallpaper routes carries a render step, because dressing the light appearance from
//! a dark session must not change what is behind the pane -- see
//! [`Route::WallpaperLight`](garage_core::schema::routes::Route::WallpaperLight) and its
//! siblings. This module's renderer is reached from [`crate::all::render_all`] and from the
//! apply side directly, never from [`crate::dispatch`].

//! # Where the render half ends
//!
//! Only `render_wallpaper()` is here. It is pure config-to-text: the resolved scheme decides
//! the fit, the path is always the `current` symlink, and nothing is resolved on disk. Its
//! three neighbours in the Python -- `current_wallpaper()`, `monitor_names()` and
//! `solid_wallpaper()` -- are all reached from `wallpaper_target()` and `apply_wallpaper()`,
//! never from here, and `solid_wallpaper()` runs `magick` as a subprocess: a renderer has no
//! [`Runner`](garage_core::traits::Runner) and structurally cannot grow one, so the whole
//! resolver belongs to `garage-apply` along with the two functions that call it. The line
//! falls exactly at `render_wallpaper()`'s own edge, which is also where the Python's own
//! purity comment puts it.

use garage_core::fs::atomic::atomic_write;
use garage_core::schema::enums::{Scheme, WallpaperSource};

use crate::cx::RenderCx;
use crate::error::RenderError;
use crate::theme::resolve_theme;

/// Write the generated `hyprpaper.conf` for the resolved theme's wallpaper, reporting whether
/// it changed (garage:3573-3608).
///
/// hyprpaper 0.8.4 reads `fit_mode` only at startup, so a changed file is exactly the set of
/// cases that need the service restarted. That is why this reports rather than restarts: the
/// restart decision belongs to the apply side.
///
/// # Errors
///
/// [`RenderError::Atomic`] if the fragment could not be written.
pub(crate) fn render_wallpaper(cx: &RenderCx<'_>) -> Result<bool, RenderError> {
    let paths = cx.paths();
    let appearance = &cx.prefs().appearance;
    let source = match resolve_theme(cx.prefs()) {
        Scheme::Light => appearance.wallpaper_light_source,
        Scheme::Dark => appearance.wallpaper_dark_source,
    };
    // A colour has no composition to preserve and its PNG is cut for the largest monitor, so
    // contain or fit would letterbox it on the smaller ones. Cover fills every display
    // whatever their aspect ratios are.
    let fit = if source == WallpaperSource::Color {
        "cover"
    } else {
        appearance.wallpaper_fit.as_str()
    };
    let text = format!(
        "# Generated by garage. Edit preferences.toml instead.
splash = false
ipc = true

wallpaper {{
    monitor =
    path = {path}
    fit_mode = {fit}
}}
",
        path = paths.wallpaper.current.display()
    );
    if std::fs::read_to_string(&paths.fragments.hyprpaper).is_ok_and(|found| found == text) {
        return Ok(false);
    }
    atomic_write(&paths.fragments.hyprpaper, &text)?;
    Ok(true)
}
