shell                       /usr/bin/fish
dynamic_background_opacity  yes
cursor_trail                0
font_family                 Geist Mono
font_size                   12.0
modify_font                 cell_height 115%
modify_font                 underline_position 2
window_padding_width        16
placement_strategy          center
cursor_shape                beam
cursor_beam_thickness       1.5
cursor_blink_interval       0.5
tab_bar_min_tabs            2
tab_bar_style               powerline
tab_powerline_style         slanted
confirm_os_window_close     0

map super+c copy_to_clipboard
map super+v paste_from_clipboard

# Palette, rewritten by garage on a theme change.
include theme.conf
