[package]
name = "garage-reconcile"
version = "0.1.0"
edition = "2021"

[lib]
name = "garage_reconcile"

[lints]
workspace = true

[dependencies]
garage-core = { path = "../garage-core" }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.145", features = ["preserve_order"] }
thiserror = "2.0.20"
