[package]
name = "garage-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "garage"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
garage-core = { path = "../garage-core" }
garage-prefs = { path = "../garage-prefs" }
garage-proc = { path = "../garage-proc" }
garage-render = { path = "../garage-render" }
garage-apply = { path = "../garage-apply" }
garage-reconcile = { path = "../garage-reconcile" }
serde_json = { version = "1.0.145", features = ["preserve_order"] }
thiserror = "2.0.20"
toml = { version = "1.1.4", features = ["preserve_order"] }
