[package]
name = "garage-reconcile"
version = "0.1.0"
edition = "2021"

[lib]
name = "garage_reconcile"

[lints]
workspace = true

[dependencies]
garage-core = { path = "../garage-core" }
garage-prefs = { path = "../garage-prefs" }
garage-proc = { path = "../garage-proc" }
garage-render = { path = "../garage-render" }
thiserror = "2.0.20"
